// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJoupOaK51MwT6NRkNb_BlZdAmohmcBXk',
    appId: '1:23035564503:web:329504a3b31dd8b282bb92',
    messagingSenderId: '23035564503',
    projectId: 'fruitshub-dcc6e',
    authDomain: 'fruitshub-dcc6e.firebaseapp.com',
    storageBucket: 'fruitshub-dcc6e.firebasestorage.app',
    measurementId: 'G-ZJFJHD1TN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFax45eXKI5Khug76xzXq_Htxa2udygs',
    appId: '1:23035564503:android:5310fcf51e30356882bb92',
    messagingSenderId: '23035564503',
    projectId: 'fruitshub-dcc6e',
    storageBucket: 'fruitshub-dcc6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi09rq3j5OZsU0MfrLne-DFNnEJHBDAmE',
    appId: '1:23035564503:ios:39c873d2f892ef0482bb92',
    messagingSenderId: '23035564503',
    projectId: 'fruitshub-dcc6e',
    storageBucket: 'fruitshub-dcc6e.firebasestorage.app',
    androidClientId: '23035564503-7hhgulinog9cbusnuq4ok54c8vajnl88.apps.googleusercontent.com',
    iosClientId: '23035564503-ic7epr9kubrdhkjv9mkuvjsph4d1aip8.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi09rq3j5OZsU0MfrLne-DFNnEJHBDAmE',
    appId: '1:23035564503:ios:39c873d2f892ef0482bb92',
    messagingSenderId: '23035564503',
    projectId: 'fruitshub-dcc6e',
    storageBucket: 'fruitshub-dcc6e.firebasestorage.app',
    androidClientId: '23035564503-7hhgulinog9cbusnuq4ok54c8vajnl88.apps.googleusercontent.com',
    iosClientId: '23035564503-ic7epr9kubrdhkjv9mkuvjsph4d1aip8.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJoupOaK51MwT6NRkNb_BlZdAmohmcBXk',
    appId: '1:23035564503:web:c79264d3658ff7c582bb92',
    messagingSenderId: '23035564503',
    projectId: 'fruitshub-dcc6e',
    authDomain: 'fruitshub-dcc6e.firebaseapp.com',
    storageBucket: 'fruitshub-dcc6e.firebasestorage.app',
    measurementId: 'G-L0NLN0MLJ6',
  );
}
